function genStarName(){

    var grec = [
        "Alpha",
        "Beta",
        "Epsilon",
        "Eta",
        "Theta",
        "Iota",
        "Upsilon",
        "Chi",
        "Omega",
        "Zeta",
        "Nu",
        "Xi",
        "Omicron",
        "Rho",
        "Sigma",
        "Tau",
        "Gamma",
        "Delta",
        "Kappa",
        "Lambda",
        "Mu",
        "Psi",
        "Phi"
    ]

    var constel = [
        "Andromeda",
        "Aquarius",
        "Aquila",
        "Ara",
        "Argo_Navis",
        "Aries",
        "Auriga",
        "Bootes",
        "Cancer",
        "Canis_Major",
        "Canis_Minor",
        "Capricornus",
        "Cassiopeia",
        "Centaurus",
        "Cepheus",
        "Cetus",
        "Australis",
        "Borealis",
        "Corvus",
        "Crater",
        "Cygnus",
        "Delphinus",
        "Draco",
        "Equuleus",
        "Eridanus",
        "Gemini",
        "Hercules",
        "Hydra",
        "Leo",
        "Lepus",
        "Libra",
        "Lupus",
        "Lyra",
        "Ophiuchus",
        "Orion",
        "Pegasus",
        "Perseus",
        "Pisces",
        "Austrinus",
        "Sagitta",
        "Sagittarius",
        "Scorpius",
        "Serpens",
        "Taurus",
        "Triangulum",
        "Ursa_Major",
        "Ursa_Minor",
        "Virgo"
    ]

    var name = grec[Math.floor(Math.random()*grec.length)]+"_"+constel[Math.floor(Math.random()*constel.length)]
    return name;
}

function genGalaxyName(){
    var constel = [
        "Andromeda",
        "Aquarius",
        "Aquila",
        "Ara",
        "Argo_Navis",
        "Aries",
        "Auriga",
        "Bootes",
        "Cancer",
        "Canis_Major",
        "Canis_Minor",
        "Capricornus",
        "Cassiopeia",
        "Centaurus",
        "Cepheus",
        "Cetus",
        "Australis",
        "Borealis",
        "Corvus",
        "Crater",
        "Cygnus",
        "Delphinus",
        "Draco",
        "Equuleus",
        "Eridanus",
        "Gemini",
        "Hercules",
        "Hydra",
        "Leo",
        "Lepus",
        "Libra",
        "Lupus",
        "Lyra",
        "Ophiuchus",
        "Orion",
        "Pegasus",
        "Perseus",
        "Pisces",
        "Austrinus",
        "Sagitta",
        "Sagittarius",
        "Scorpius",
        "Serpens",
        "Taurus",
        "Triangulum",
        "Ursa_Major",
        "Ursa_Minor",
        "Virgo"
    ]

    var name = constel[Math.floor(Math.random()*constel.length)]
    return name;
}